WPE_GeneratorsOfGroup := function(G)
    gens := GeneratorsOfGroup(G);
    if IsEmpty(gens) then
        gens := [()];
    fi;
    return gens;
end;

Generate := function(K, H, stream)
    local G, size;
    G := WreathProductImprimitiveAction(K, H);
    AppendTo(stream, "#\n");
    AppendTo(stream, "gap> K := Group(", WPE_GeneratorsOfGroup(K), ");;\n");
    AppendTo(stream, "gap> H := Group(", WPE_GeneratorsOfGroup(H), ");;\n");
    p := ExtRepPolynomialRatFun(CycleIndex(G));
    AppendTo(stream, "gap> p := ", p, ";;\n");
    AppendTo(stream, "gap> TestCycleIndexImprimitiveAction(K, H, p);\n");
    AppendTo(stream, "true\n\n");
end;

filename := "testCycleIndexImprimitiveAction.tst";
file := Concatenation("out/", filename);
stream:=OutputTextFile(file, false);
SetPrintFormattingStatus(stream, false);
PrintTo(stream);
AppendTo(stream, "# Generated by dev/tests/cycleIndexIA/generate.g\n");
AppendTo(stream, "# Do not edit this file manually!\n");
AppendTo(stream, "gap> START_TEST(\"", filename, "\");\n");
AppendTo(stream, "gap> ReadPackage(\"WPE\",\"tst/testCycleIndex.g\");;\n\n");

K := SymmetricGroup(1);
H := SymmetricGroup(1);
Generate(K, H, stream);

K := SymmetricGroup(1);
H := SymmetricGroup(5);
Generate(K, H, stream);

K := SymmetricGroup(1);
H := AlternatingGroup(5);
Generate(K, H, stream);

K := SymmetricGroup(4);
H := SymmetricGroup(1);
Generate(K, H, stream);

K := AlternatingGroup(4);
H := SymmetricGroup(1);
Generate(K, H, stream);

K := SymmetricGroup(4);
H := SymmetricGroup(5);
Generate(K, H, stream);

K := SymmetricGroup(4);
H := AlternatingGroup(5);
Generate(K, H, stream);

K := SymmetricGroup(4);
H := DihedralGroup(IsPermGroup, 10);
Generate(K, H, stream);

K := SymmetricGroup(4);
H := Group((1,2,3)(4,5));
Generate(K, H, stream);

AppendTo(stream, "#\n");
AppendTo(stream, "gap> STOP_TEST(\"", filename, "\");\n");
